### ISSUE TITLE
Button Text UI

### ISSUE THREAD

**Issue by Siddhant-K-code** [GDGVIT/akina#2]
The Text on Button on your website is working fine, please fix.

![image](https://user-images.githubusercontent.com/55068936/85871486-16266000-b7ec-11ea-82b9-ca99382cbc21.png)

**Comment by searchformyusername** [comment]
@Siddhant-K-code I tried to reproduce this UI bug but couldn't
Can you please tell what browser you are using and version also (I tried it on Firefox Chrome Edge)

**Comment by Siddhant-K-code** [comment]
Microsoft Edge Latest Version

**Comment by searchformyusername** [comment]
@Siddhant-K-code **I couldn't recreate this UI bug**. This page is fully responsive,
A possible reason can be some loading issue and maybe you don't get this any other time you visit.
Some Extention can also be a possible reason if you are having this every time.

**Comment by Siddhant-K-code** [comment]
i am getting this every time, even browser zoom is set on 100%, just default settings

**Comment by Siddhant-K-code** [comment]
but, its fine on Mobile browser.

**Comment by searchformyusername** [comment]
> 
> 
> i am getting this every time, even browser zoom is set on 100%, just default settings

Yes, If someone is able to recreate this error with possible reason then it will be fixed.
Thankyou for informing :)
